version: 2.1

jobs:
  co:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod tidy
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_artifacts:
          path: /tmp/test-reports
          destination: artifact-file
      - persist_to_workspace:
          root: .
          paths: [./* ]
  rotate-iam-key:
    docker:
      - image: circleci/golang:1.17
        auth:
          username: ${DH_USER}
          password: ${DH_PASS}
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'IAM key/pair rotator'
          command: |
            go build
            ./iam-user-key-rotator --circleci "${CIRCLE_TOKEN}"

workflows:
  wip:
    jobs:
      - co:
          context: [ testing ]
      - rotate-iam-key:
          requires: [ co ]
          context: [ orb-publishing, testing ]